modLoader="javafml"
loaderVersion="${mod_loader_version}"
issueTrackerURL="https://minecraft.curseforge.com/projects/advanced-shulkerboxes/issues"
displayURL="http://minecraft.curseforge.com/projects/advanced-shulkerboxes"
# logoFile="shulkerbox.png"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_vendor}"
# credits=""
updateJSONURL="https://maxhenkel.de/update/shulkerbox.json"
description='''Open Shulkerboxes in your hand'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"